name: CLI Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: swift-actions/setup-swift@v2

      - name: Build
        run: |
          cd cli
          swift build -c release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: cli/.build/release/HomeObserver